plugins {
    id 'java'
    id 'application'
    id 'com.google.osdetector' version '1.7.3'
}

group = 'com.aws.valkey'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'io.valkey', name: 'valkey-glide', version: '2.+', classifier: osdetector.classifier
}

application {
    mainClass = 'ClusterOperations'
}
