services:
  valkey:
    image: valkey/valkey:8.1.1
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "valkey-cli", "PING"]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - valkey-data:/data

volumes:
  valkey-data:
